//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Khach_San_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRoom
    {
        public int BookingID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<double> Rating { get; set; }
    
        public virtual User User { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
    }
}
