//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Khach_San_2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BookRooms = new HashSet<BookRoom>();
        }
    
        public int RoomID { get; set; }
        public string RoomNumber { get; set; }
        public string TypeRoom { get; set; }
        public int Price { get; set; }
        public byte[] ImgRoom { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookRoom> BookRooms { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual TypeRoom TypeRoom1 { get; set; }
    }
}
